// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_id.proto

package com.cwa.tribe.messages;

public final class MsgId {
  private MsgId() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code tribe.MsgID}
   */
  public enum MsgID
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>MSG_LOGIN = 1;</code>
     */
    MSG_LOGIN(0, 1),
    ;

    /**
     * <code>MSG_LOGIN = 1;</code>
     */
    public static final int MSG_LOGIN_VALUE = 1;


    public final int getNumber() { return value; }

    public static MsgID valueOf(int value) {
      switch (value) {
        case 1: return MSG_LOGIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
            public MsgID findValueByNumber(int number) {
              return MsgID.valueOf(number);
            }
          };

    private final int value;

    private MsgID(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tribe.MsgID)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
